_problem_:
  data_dim: &data_dim 2
  n_classes: &n_classes 2

train:
  n_iters: 100_000
  inner_problem_iters: 5
  batch_size: 512
  run_dir: /Users/shlenskii/Desktop/github/pfgmpp/artifacts/ibmd/toy/gaussians/11

eval:
  log_every: 500
  eval_every: 500
  callbacks:
    - _target_: ibmd.training.callbacks.TwoDimCallback
      sample_size: 10_000

ibmd:
  other:
    n_steps: 4
    ema_decay: 0.99
    n_classes: *n_classes
    remove_dropout: True

  teacher:
    dynamics:
      _target_: pfgmpp.core.PFGMPP
      data_dim: *data_dim
      sigma_min: 0.002
      sigma_max: 50.0
      D: 2048

    loss:
      _target_: pfgmpp.training.losses.TargetPredictionLoss
      sigma_prior_mode: log_normal
      loss_weights_mode: edm

    loss_for_student:
      _target_: pfgmpp.training.losses.TargetPredictionLoss
      sigma_prior_mode: log_normal
      loss_weights_mode: edm

    net:
      _target_: pfgmpp.training.networks.TimeConditionedMLP
      dim: *data_dim
      hidden_dim: 64
      n_layers: 3
      out_dim: *data_dim
      n_classes: *n_classes

    ckpt_path: /Users/shlenskii/Desktop/github/pfgmpp/artifacts/notebooks_outputs/toy/gaussians/conditional/11.pt

  student:
    net_optimizer: &net_optimizer
      lr: 1e-4

    data_estimator_net_optimizer: *net_optimizer
