problem:
  img_channels: &img_channels 3
  img_resolution: &img_resolution 32
  data_dim: &data_dim 3072
  n_classes: &n_classes 10

  teacher_ckpt_dir: pfgmpp_orig
  teacher_ckpt_name: cifar10_ncsnpp_D_2048_conditional

train:
  n_iters: 100_000
  inner_problem_iters: 5
  batch_size: 256 
  run_dir: ibmd/${problem.teacher_ckpt_dir}/${problem.teacher_ckpt_name}

eval:
  log_every: 50
  eval_every: 100
  callback:
    _target_: ibmd.training.callbacks.ImageDataCallback
    n_classes: *n_classes
    sample_size_per_class: 2
    img_channels: *img_channels
    img_resolution: *img_resolution

ibmd:
  n_classes: *n_classes
  ema_decay: 0.99

  teacher:
    dynamics:
      _target_: pfgmpp.core.PFGMPP
      data_dim: *data_dim
      sigma_min: 0.002
      sigma_max: 80.0
      D: 2048

    loss:
      _target_: pfgmpp.training.losses.EDMLoss

    img_channels: *img_channels
    img_resolution: *img_resolution

    ckpt_path: ${problem.teacher_ckpt_dir}/${problem.teacher_ckpt_name}.pkl

  student:
    net_optimizer:
      lr: 1e-4

    data_estimator_net_optimizer:
      lr: 1e-4
